name: mailerLambdaCI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: GitGuardian scan
        uses: GitGuardian/ggshield/actions/secret@v1.31.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  build:
    runs-on: ubuntu-latest
    needs: scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install-dependencies
        run: cd src && pip install -r requirements.txt -t ./package

      - name: run tests
        run: echo "Tests are not implemented yet"

      - name: install zip tool
        uses: montudor/action-zip@v1

      - name: zip lambda function
        run: |
          cd src
          mkdir -p ./package
          cp send_mail.py ./package
          cd package
          zip -r code.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: ./src/package/code.zip
          overwrite: true
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: get artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: ./

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: deploy lambda_function
        run: aws lambda update-function-code --function-name send_mail_function --zip-file fileb://code.zip
